"""
@author: Anonymous Name
@email:  Anonymous Email
"""

from yacs.config import CfgNode as CN

_C = CN()

_C.MODEL = CN()
_C.MODEL.NAME = ''
_C.MODEL.WEIGHTS = ''
_C.MODEL.BIAS = False
_C.MODEL.FIND_UNUSED_PARAMETERS = False
_C.MODEL.SOURCE_CSET = 0.
_C.MODEL.SOURCE_OSET = 0.
_C.MODEL.TARGET_OSET = 0.
_C.MODEL.MIXUP = 0.
_C.MODEL.CC = 0.
_C.MODEL.NEIGHBOR = 0.

_C.MODEL.ALPHA = 0.
_C.MODEL.NEIGHBOR_EPS = 0.
_C.MODEL.SCALE = 0.
_C.MODEL.NUM_K = 0

_C.DATASET = CN()
_C.DATASET.SOURCE = ''
_C.DATASET.TARGET = ''
_C.DATASET.SHARED = 0
_C.DATASET.SOURCE_PRIVATE = 0
_C.DATASET.TARGET_PRIVATE = 0
_C.DATASET.TRAIN_TRANSFORM = ''
_C.DATASET.EVAL_TRANSFORM = ''

_C.OPTIMIZER = CN()
_C.OPTIMIZER.FT_LR = 0.
_C.OPTIMIZER.NEW_LR = 0.
_C.OPTIMIZER.MOMENTUM = 0.
_C.OPTIMIZER.WEIGHT_DECAY = 0.

_C.SCHEDULER = CN()
_C.SCHEDULER.GAMMA = 0.
_C.SCHEDULER.POWER = 0.

_C.ENGINE = CN()
_C.ENGINE.ITERS = 0
_C.ENGINE.WARMUP_ITERS = 0
_C.ENGINE.BATCH_SIZE = 0
_C.ENGINE.EVAL_BATCH_SIZE = 0
_C.ENGINE.NUM_WORKERS = 0
_C.ENGINE.ALLOW_TF32 = False
_C.ENGINE.ENABLE_AMP = False
_C.ENGINE.PIN_MEMORY = False
_C.ENGINE.DETERMINISTIC = False

_C.MISC = CN()
_C.MISC.OUTPUT_DIR = ''
_C.MISC.SUFFIX = ''
_C.MISC.SEED = 0
_C.MISC.PRINT_FREQ = 0
_C.MISC.EVAL_FREQ = 0