MODEL:
  NAME: 'OVANet'
  WEIGHTS: 'IMAGENET1K_V1'
  BIAS: False
  FIND_UNUSED_PARAMETERS: False

  SOURCE_CSET: 1.0
  SOURCE_OSET: 0.5
  TARGET_OSET: 0.1

DATASET:
  SOURCE: 'data/splits/OfficeHome/CDA/source_clipart_cda.txt'
  TARGET: 'data/splits/OfficeHome/CDA/target_real_cda.txt'
  SHARED: 65
  SOURCE_PRIVATE: 0
  TARGET_PRIVATE: 0
  TRAIN_TRANSFORM: 'DEFAULT_TRAIN'
  EVAL_TRANSFORM: 'DEFAULT_EVAL'

OPTIMIZER:
  FT_LR: 0.001
  NEW_LR: 0.01
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005

SCHEDULER:
  GAMMA: 10.0
  POWER: 0.75

ENGINE:
  ITERS: 10000
  BATCH_SIZE: 36
  EVAL_BATCH_SIZE: 256
  NUM_WORKERS: 8
  ALLOW_TF32: False
  ENABLE_AMP: False
  PIN_MEMORY: True

MISC:
  OUTPUT_DIR: 'runs/OVANet/OfficeHome/CDA/clipart2real'
  SEED: 2023
  PRINT_FREQ: 10
  EVAL_FREQ: 500