MODEL:
  NAME: 'MLNet'
  WEIGHTS: 'IMAGENET1K_V1'
  BIAS: False
  FIND_UNUSED_PARAMETERS: False

  SOURCE_CSET: 1.0
  SOURCE_OSET: 0.5
  TARGET_OSET: 0.1
  MIXUP: 0.1
  CC: 0.16
  NEIGHBOR: 0.5

  ALPHA: 2.0
  NEIGHBOR_EPS: 0.875
  SCALE: 10.0

DATASET:
  SOURCE: 'data/splits/OfficeHome/OPDA/source_real_opda.txt'
  TARGET: 'data/splits/OfficeHome/OPDA/target_art_opda.txt'
  SHARED: 10
  SOURCE_PRIVATE: 5
  TARGET_PRIVATE: 50
  TRAIN_TRANSFORM: 'DEFAULT_TRAIN'
  EVAL_TRANSFORM: 'DEFAULT_EVAL'

OPTIMIZER:
  FT_LR: 0.001
  NEW_LR: 0.01
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005

SCHEDULER:
  GAMMA: 10.0
  POWER: 0.75

ENGINE:
  ITERS: 10000
  WARMUP_ITERS: 200
  BATCH_SIZE: 36
  EVAL_BATCH_SIZE: 256
  NUM_WORKERS: 8
  ALLOW_TF32: False
  ENABLE_AMP: False
  PIN_MEMORY: True

MISC:
  OUTPUT_DIR: 'runs/MLNet/OfficeHome/OPDA/real2art'
  SEED: 2023
  PRINT_FREQ: 10
  EVAL_FREQ: 500